version: '3.7'
services:
    sqlserver1:
        image: mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-18.04
        ports:  
          - "11433:1433"
        env_file:
          - sqlserver.env
          - sapassword.env
        volumes: 
          - /var/opt/mssql \